// Code generated by goctl. DO NOT EDIT!
// Source: student.proto

package server

import (
	"context"

	"demacia/datacenter/student/rpc/internal/logic"
	"demacia/datacenter/student/rpc/internal/svc"
	"demacia/datacenter/student/rpc/student"
)

type StudentServer struct {
	svcCtx *svc.ServiceContext
}

func NewStudentServer(svcCtx *svc.ServiceContext) *StudentServer {
	return &StudentServer{
		svcCtx: svcCtx,
	}
}

func (s *StudentServer) FindOneById(ctx context.Context, in *student.IdRequest) (*student.StudentResponse, error) {
	l := logic.NewFindOneByIdLogic(ctx, s.svcCtx)
	return l.FindOneById(in)
}

func (s *StudentServer) FindOneByUserName(ctx context.Context, in *student.UserNameRequest) (*student.StudentResponse, error) {
	l := logic.NewFindOneByUserNameLogic(ctx, s.svcCtx)
	return l.FindOneByUserName(in)
}
