// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/datacenter/member/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/member/list",
					Handler: ListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/detail",
					Handler: DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/delete",
					Handler: DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/status",
					Handler: StatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/insert",
					Handler: InsertHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/update",
					Handler: UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/import",
					Handler: ImportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/member/choice",
					Handler: ChoiceHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
