// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/datacenter/common/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/common/area",
				Handler: areaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/common/ethnic",
				Handler: ethnicHandler(serverCtx),
			},
		},
	)
}
