// Code generated by goctl. DO NOT EDIT!
// Source: card.proto

package server

import (
	"context"

	"demacia/datacenter/card/rpc/card"
	"demacia/datacenter/card/rpc/internal/logic"
	"demacia/datacenter/card/rpc/internal/svc"
)

type CardServer struct {
	svcCtx *svc.ServiceContext
	card.UnimplementedCardServer
}

func NewCardServer(svcCtx *svc.ServiceContext) *CardServer {
	return &CardServer{
		svcCtx: svcCtx,
	}
}

func (s *CardServer) AddTeacherCard(ctx context.Context, in *card.AddReq) (*card.BoolResp, error) {
	l := logic.NewAddTeacherCardLogic(ctx, s.svcCtx)
	return l.AddTeacherCard(in)
}

func (s *CardServer) AddStudentCard(ctx context.Context, in *card.AddReq) (*card.BoolResp, error) {
	l := logic.NewAddStudentCardLogic(ctx, s.svcCtx)
	return l.AddStudentCard(in)
}

func (s *CardServer) GetTeacherCardList(ctx context.Context, in *card.ListReq) (*card.ListResp, error) {
	l := logic.NewGetTeacherCardListLogic(ctx, s.svcCtx)
	return l.GetTeacherCardList(in)
}

func (s *CardServer) GetStudentCardList(ctx context.Context, in *card.ListReq) (*card.ListResp, error) {
	l := logic.NewGetStudentCardListLogic(ctx, s.svcCtx)
	return l.GetStudentCardList(in)
}

func (s *CardServer) CheckMember(ctx context.Context, in *card.CheckReq) (*card.BoolResp, error) {
	l := logic.NewCheckMemberLogic(ctx, s.svcCtx)
	return l.CheckMember(in)
}

func (s *CardServer) CheckStudent(ctx context.Context, in *card.CheckReq) (*card.BoolResp, error) {
	l := logic.NewCheckStudentLogic(ctx, s.svcCtx)
	return l.CheckStudent(in)
}
