// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	DeviceId int64 `json:"device_id"`
}

type TimeSwitchInfo struct {
	HolidayFlag   int8             `json:"holiday_flag"`
	DeviceIds     []int64          `json:"device_ids,omitempty"`
	SpecialDate   []*DateRange     `json:"special_date"`
	TimeRangeList []*TimeRangeList `json:"time_range_list"`
}

type DateRange struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type TimeRange struct {
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type TimeRangeList struct {
	Weekday   int8         `json:"weekday"`
	TimeRange []*TimeRange `json:"time_range"`
}

type SuccessResp struct {
	Success bool `json:"success"`
}
