// Code generated by goctl. DO NOT EDIT.
package types

type OrgAddReq struct {
	Title        string `json:"title"`
	TrueName     string `json:"true_name"`
	Mobile       string `json:"mobile"`
	UserName     string `json:"user_name"`
	Password     string `json:"password"`
	ActivateDate string `json:"activate_date"`
	ExpireDate   string `json:"expire_date"`
	Addr         string `json:"addr"`
	Msg          string `json:"msg"`
	AgentId      int64  `json:"agent_id"`
	TermId       int64  `json:"term_id"`
	AreaId       int64  `json:"area_id"`
	IsSchool     int8   `json:"is_school"`
}

type OrgUpdateReq struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	TrueName     string `json:"true_name"`
	Mobile       string `json:"mobile"`
	ActivateDate string `json:"activate_date"`
	ExpireDate   string `json:"expire_date"`
	Addr         string `json:"addr"`
	Msg          string `json:"msg"`
	AreaId       int64  `json:"area_id"`
}

type IdReq struct {
	Id int64 `json:"id"`
}

type OrgListReq struct {
	Title      string `json:"title"`
	ProvinceId int64  `json:"province_id"`
	CityId     int64  `json:"city_id"`
	AreaId     int64  `json:"area_id"`
	Page       int    `json:"page"`
	Limit      int    `json:"limit"`
}

type OrgInfo struct {
	Id           int64  `json:"id"`
	AreaTitle    string `json:"area_title"`
	Title        string `json:"title"`
	ActivateDate string `json:"activate_date"`
	ExpireDate   string `json:"expire_date"`
	TrueName     string `json:"true_name"`
	Mobile       string `json:"mobile"`
	UserName     string `json:"user_name"`
	Addr         string `json:"addr"`
	Msg          string `json:"msg"`
	CreatedTime  int64  `json:"create_time"`
	OrgStatus    int8   `json:"org_status"`
}

type OrgListResp struct {
	Count int64      `json:"count"`
	List  []*OrgInfo `json:"list"`
}
