// Code generated by goctl. DO NOT EDIT!
// Source: common.proto

package server

import (
	"context"

	"demacia/datacenter/common/rpc/common"
	"demacia/datacenter/common/rpc/internal/logic"
	"demacia/datacenter/common/rpc/internal/svc"
)

type CommonServer struct {
	svcCtx *svc.ServiceContext
}

func NewCommonServer(svcCtx *svc.ServiceContext) *CommonServer {
	return &CommonServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonServer) FindAreaInfo(ctx context.Context, in *common.AreaReq) (*common.AreaResp, error) {
	l := logic.NewFindAreaInfoLogic(ctx, s.svcCtx)
	return l.FindAreaInfo(in)
}

func (s *CommonServer) FindHolidayInfo(ctx context.Context, in *common.HolidayReq) (*common.HolidayResp, error) {
	l := logic.NewFindHolidayInfoLogic(ctx, s.svcCtx)
	return l.FindHolidayInfo(in)
}
