// Code generated by goctl. DO NOT EDIT.
package types

type Id struct {
	Id int64 `json:"id"`
	*PageListReq
}

type Title struct {
	Title string `json:"title"`
}

type Info struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
}

type ListRespose struct {
	List []Info `json:"list"`
}

type StageInfo struct {
	Id    int64  `json:"id,optional"`
	Title string `json:"title"`
	Year  int64  `json:"year"`
}

type StageListRespose struct {
	List []*StageInfo `json:"list"`
}

type Teacher struct {
	Id       int64  `json:"id"`
	TrueName string `json:"true_name"`
}

type ClassCompletionReq struct {
	StageId int64 `json:"stage_id"`
	GradeId int64 `json:"grade_id"`
	Num     int8  `json:"num,default=1,optional"`
}

type PageListReq struct {
	StageId     int64  `json:"stage_id,optional"`
	GradeId     int64  `json:"grade_id,optional"`
	ClassId     int64  `json:"class_id,optional"`
	TeacherName string `json:"teacher_name,optional"`
	Page        int    `json:"page,optional,defult=1"`
	Limit       int    `json:"limit,optional,default=15"`
}

type ClassInfo struct {
	Id            int64      `json:"id"`
	StageId       int64      `json:"stage_id"`
	GradeId       int64      `json:"grade_id"`
	StageTitle    string     `json:"stage_title"`
	FullName      string     `json:"full_name"`
	AliasName     string     `json:"alias_name"`
	Class_teacher []*Teacher `json:"class_teacher"`
	Desc          string     `json:"desc"`
	MemberNum     int64      `json:"member_num"`
}

type AddClassReq struct {
	Id          int64   `json:"id,optional"`
	StageId     int64   `json:"stage_id"`
	GradeId     int64   `json:"grade_id"`
	AliasName   string  `json:"alias_name,optional"`
	TeacherId   []int64 `json:"teacher_id,optional"`
	Description string  `json:"description,optional"`
	Sort        int8    `json:"sort"`
}

type BatchAddClassReq struct {
	StageId    int64 `json:"stage_id"`
	GradeId    int64 `json:"grade_id"`
	Completion int8  `json:"completion"`
	Num        int8  `json:"num"`
}

type ClassListRespose struct {
	List  []*ClassInfo `json:"list"`
	Total int          `json:"total"`
	Limit int          `json:"limit"`
}

type ListStageGradeInfo struct {
	Id     int64   `json:"id"`
	Title  string  `json:"title"`
	Grades []*Info `json:"grades"`
}

type ListGradeByOrgResp struct {
	List []*ListStageGradeInfo `json:"list"`
}

type TreeClassResp struct {
	Id       int64           `json:"id"`
	Name     string          `json:"name"`
	Num      int64           `json:"num"`
	Children []TreeClassResp `json:"children"`
}

type AddTeachReq struct {
	ClassId   int64 `json:"class_id"`
	SubjectId int64 `json:"subject_id"`
	TeacherId int64 `json:"teacher_id"`
}

type UpdateTeachReq struct {
	ClassId   int64 `json:"class_id"`
	SubjectId int64 `json:"subject_id"`
	TeacherId int64 `json:"teacher_id"`
}

type TeachResp struct {
	Id           int64  `json:"id"`
	ClassId      int64  `json:"class_id"`
	SubjectId    int64  `json:"subject_id"`
	SubjectTitle string `json:"subject_title"`
	TeacherId    int64  `json:"teacher_id"`
	TeacherName  string `json:"teacher_name"`
}

type DeleteTeachReq struct {
	ClassId   int64 `json:"class_id"`
	SubjectId int64 `json:"subject_id"`
}

type ListTeachResp struct {
	List []TeachResp `json:"list"`
}
