// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/cloudscreen/ticket/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/ticket/add",
				Handler: addHandler(serverCtx),
			},
		},
	)
}
