// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/cloudscreen/timeswitch/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/timeswitch/info",
					Handler: GetTimeSwitchInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/timeswitch/edit",
					Handler: EditTimeSwitchInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
