// Code generated by goctl. DO NOT EDIT!
// Source: position.proto

package server

import (
	"context"
	"demacia/datacenter/position/rpc/internal/logic"
	"demacia/datacenter/position/rpc/internal/svc"
	"demacia/datacenter/position/rpc/position"
)

type PositionServer struct {
	svcCtx *svc.ServiceContext
}

func NewPositionServer(svcCtx *svc.ServiceContext) *PositionServer {
	return &PositionServer{
		svcCtx: svcCtx,
	}
}

func (s *PositionServer) FindByClassId(ctx context.Context, in *position.ClassIdReq) (*position.PositionInfo, error) {
	l := logic.NewFindByClassIdLogic(ctx, s.svcCtx)
	return l.FindByClassId(in)
}

func (s *PositionServer) FindById(ctx context.Context, in *position.PositionIdReq) (*position.PositionInfo, error) {
	l := logic.NewFindByPositionIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}
