// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/datacenter/student/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/student/import",
				Handler: importStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/insert",
				Handler: insertStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/update",
				Handler: updateStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/delete",
				Handler: deleteStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/page-list",
				Handler: studentsListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/detail",
				Handler: studentsDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/export",
				Handler: exportStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/student/list",
				Handler: classStudentsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
