// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/service/event/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/event/category/insert",
				Handler: CategoryInsertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/category/update",
				Handler: CategoryUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/category/delete",
				Handler: CategoryDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/category/list",
				Handler: CategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/insert",
				Handler: EventInsertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/update",
				Handler: EventUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/delete",
				Handler: EventDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/detail",
				Handler: EventDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/event/list",
				Handler: EventListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
