// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/datacenter/position/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/position/add",
					Handler: PositionAddHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/position/list",
					Handler: PositionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/position/generate",
					Handler: GeneratePositionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/position/edit",
					Handler: PositionEditHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/position/remove",
					Handler: PositionRemoveHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
