// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/service/auth/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/member/login",
				Handler: memberLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/user/login",
				Handler: userLoginHandler(serverCtx),
			},
		},
	)
}
