// Code generated by goctl. DO NOT EDIT!
// Source: department.proto

package server

import (
	"context"

	"demacia/datacenter/department/rpc/department"
	"demacia/datacenter/department/rpc/internal/logic"
	"demacia/datacenter/department/rpc/internal/svc"
)

type DepartmentServer struct {
	svcCtx *svc.ServiceContext
	department.UnimplementedDepartmentServer
}

func NewDepartmentServer(svcCtx *svc.ServiceContext) *DepartmentServer {
	return &DepartmentServer{
		svcCtx: svcCtx,
	}
}

//  根据id获取部门详情
func (s *DepartmentServer) GetDepartmentById(ctx context.Context, in *department.DepartmentIdReq) (*department.DepartmentInfo, error) {
	l := logic.NewGetDepartmentByIdLogic(ctx, s.svcCtx)
	return l.GetDepartmentById(in)
}

//  根据机构ID和部门名称获取部门信息
func (s *DepartmentServer) GetDepartmentByOrgIdAndDepartmentTitle(ctx context.Context, in *department.OrgIdAndDepartmentTitleReq) (*department.DepartmentInfo, error) {
	l := logic.NewGetDepartmentByOrgIdAndDepartmentTitleLogic(ctx, s.svcCtx)
	return l.GetDepartmentByOrgIdAndDepartmentTitle(in)
}

//  根据机构ID和部门ID获取部门下的人员ID列表
func (s *DepartmentServer) GetMemberIdsByOrgIdAndDepartmentId(ctx context.Context, in *department.OrgIdAndDepartmentIdReq) (*department.MemberIdsResp, error) {
	l := logic.NewGetMemberIdsByOrgIdAndDepartmentIdLogic(ctx, s.svcCtx)
	return l.GetMemberIdsByOrgIdAndDepartmentId(in)
}

//  根据机构ID和人员ID获取该人员所在的部门ID列表
func (s *DepartmentServer) GetDepartmentIdsByOrgIdAndMemberId(ctx context.Context, in *department.OrgIdAndMemberIdReq) (*department.DepartmentIdsResp, error) {
	l := logic.NewGetDepartmentIdsByOrgIdAndMemberIdLogic(ctx, s.svcCtx)
	return l.GetDepartmentIdsByOrgIdAndMemberId(in)
}

//  根据机构ID获取所有的部门
func (s *DepartmentServer) GetDepartmentsByOrgId(ctx context.Context, in *department.OrgIdReq) (*department.DepartmentListResp, error) {
	l := logic.NewGetDepartmentsByOrgIdLogic(ctx, s.svcCtx)
	return l.GetDepartmentsByOrgId(in)
}

//  根据机构ID获取所有的部门人员关系
func (s *DepartmentServer) GetDepartmentMemberRelationByOrgId(ctx context.Context, in *department.OrgIdReq) (*department.DepartmentMembersResp, error) {
	l := logic.NewGetDepartmentMemberRelationByOrgIdLogic(ctx, s.svcCtx)
	return l.GetDepartmentMemberRelationByOrgId(in)
}
