// Code generated by goctl. DO NOT EDIT.
package types

type Id struct {
	Id int64 `json:"id"`
}

type AddSubjectReq struct {
	Title  string  `json:"title"`
	Grades []int64 `json:"grades"`
}

type Ids struct {
	Id []int64 `json:"id"`
}

type UpdateSubjectReq struct {
	Id     int64   `json:"id"`
	Title  string  `json:"title"`
	Grades []int64 `json:"grades"`
}

type Grade struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
}

type Info struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
}

type SubjectListResp struct {
	Id     int64   `json:"id"`
	Title  string  `json:"title"`
	Grades []Grade `json:"grades"`
}

type SubjectListsResp struct {
	List []SubjectListResp `json:"list"`
}

type GradeManageReq struct {
	Id     int64   `json:"id"`
	Grades []int64 `json:"grades"`
}

type TeacherManageReq struct {
	Id       int64   `json:"id"`
	Teachers []int64 `json:"teachers"`
}

type SubjectTeacherResp struct {
	Id       int64  `json:"id"`
	TrueName string `json:"true_name"`
}

type ListSubjectTeacherResp struct {
	List []SubjectTeacherResp `json:"list"`
}

type TitleReq struct {
	GradeId int64  `json:"grade_id,optional"`
	Title   string `json:"title,optional"`
}
