// Code generated by goctl. DO NOT EDIT.
package types

type Id struct {
	Id int64 `json:"id"`
}

type Ids struct {
	Ids []int64 `json:"ids"`
}

type TitleReq struct {
	Title string `json:"title"`
}

type IdTitleReq struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
}

type Info struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
	Url   string `json:"images,optional"`
}

type ListReq struct {
	Title string `json:"title,optional"`
	Page  int    `json:"page,optional,default=1"`
	Limit int    `json:"limit,optional,default=10"`
}

type List struct {
	List  []Info `json:"list"`
	Total int    `json:"total"`
}

type PhotosCommonField struct {
	FolderId int64 `json:"folder_id,optional,default=0"`
	DeviceId int64 `json:"device_id,optional,default=0"`
	PhotoId  int64 `json:"photo_id,optional,default=0"`
}

type ListPhotoReq struct {
	PhotosCommonField
	ListReq
}

type RenameReq struct {
	PhotosCommonField
	IdTitleReq
}

type DeviceSelectorReq struct {
	DeviceIds      []int64 `json:"device_ids,optional"`
	DeviceGroupIds []int64 `json:"device_group_ids,optional"`
}

type TimeField struct {
	ScreenSaverWaitTime  int    `json:"screensaver_wait_time,optional"`  // 屏保等待时间
	PublishStartTime     string `json:"publish_start_time,optional"`     // 发布开始时间
	PublishEndTime       string `json:"publish_end_time,optional"`       // 发布结束时间
	ScreenSaverStartTime string `json:"screensaver_start_time,optional"` // 屏保开始时间
	ScreenSaverEndTime   string `json:"screensaver_end_time,optional"`   // 屏保结束时间
	LockScreenStartTime  string `json:"lockscreen_start_time,optional"`  // 锁屏开始时间
	LockScreenEndTime    string `json:"lockscreen_end_time,optional"`    // 锁屏结束时间
	ToppingStart         string `json:"topping_start_time,optional"`     // 置顶开始时间
	ToppingEnd           string `json:"topping_end_time,optional"`       // 置顶结束时间
}

type EditReq struct {
	PhotosCommonField
	DeviceSelectorReq
	TimeField
}

type DeleteReq struct {
	PhotosCommonField
	Ids
}

type PhotoInfo struct {
	Id                int64  `json:"id"`
	Title             string `json:"title"`
	Url               string `json:"url"`
	CreatedTime       string `json:"created_time"`
	PublishStatus     int    `json:"publish_status"`      // 发布状态
	ScreenSaverStatus int    `json:"screen_saver_status"` // 屏保状态
	LockScreenStatus  int    `json:"lock_screen_status"`  // 锁屏状态
	ToppingStatus     int    `json:"topping_status"`      // 置顶状态
}

type ListPhoto struct {
	List  []PhotoInfo `json:"list"`
	Total int         `json:"total"`
}
