// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	TrueName string `json:"true_name"`
	UserName string `json:"user_name"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}
