// Code generated by goctl. DO NOT EDIT.
package types

type Member struct {
	MemberId   int64  `json:"member_id"`
	UserName   string `json:"user_name"`
	TrueName   string `json:"true_name"`
	Mobile     string `json:"mobile"`
	Face       string `json:"face_url"`
	Avatar     string `json:"avatar"`
	JoinTime   string `json:"join_time"`
	Pid        int64  `json:"pid"`
	Status     int8   `json:"status"`
	FaceStatus int8   `json:"face_status"`
}

type Detail struct {
	MemberId   int64    `json:"member_id"`
	UserName   string   `json:"user_name"`
	TrueName   string   `json:"true_name"`
	Mobile     string   `json:"mobile"`
	Face       string   `json:"face_url"`
	Avatar     string   `json:"avatar"`
	JoinTime   string   `json:"join_time"`
	Pid        int64    `json:"pid"`
	Cards      []string `json:"cards"`
	Status     int8     `json:"status"`
	FaceStatus int8     `json:"face_status"`
	Sex        int8     `json:"sex"`
}

type MemberId struct {
	MemberId int64 `json:"member_id"`
}

type MemberIds struct {
	MemberIds []int64 `json:"member_ids"`
}

type ListReq struct {
	TrueName   string `json:"true_name,optional"`
	Page       int    `json:"page,default=1"`
	Limit      int    `json:"limit,default=12"`
	FaceStatus int8   `json:"face_status,optional=0|-1|1|2,default=-2"`
}

type ListRes struct {
	List  []Member `json:"list"`
	Count int64    `json:"count"`
}

type StatusReq struct {
	MemberId int64 `json:"member_id"`
	Status   int64 `json:"status,options=1|-1"`
}

type InsertReq struct {
	UserName string   `json:"user_name"`
	TrueName string   `json:"true_name"`
	Mobile   string   `json:"mobile"`
	Cards    []string `json:"cards,optional"`
	Avatar   string   `json:"avatar_url,optional"`
	Face     string   `json:"face_url,optional"`
	Sex      int8     `json:"sex,options=0|1,default=0"`
}

type UpdateReq struct {
	MemberId int64    `json:"member_id"`
	UserName string   `json:"user_name"`
	TrueName string   `json:"true_name"`
	Mobile   string   `json:"mobile"`
	Cards    []string `json:"cards,optional"`
	Avatar   string   `json:"avatar_url,optional"`
	Face     string   `json:"face_url,optional"`
	Sex      int8     `json:"sex,options=0|1,default=0"`
}

type ImportReq struct {
	WebsocketUuid string `json:"websocket_uuid"`
	Url           string `json:"url"`
}

type MemberChoiceRes struct {
	DepartmentList []DepartmentInfo `json:"departments"`
}

type DepartmentInfo struct {
	DepartmentId    int64    `json:"department_id"`
	Count           int64    `json:"count"`
	DepartmentTitle string   `json:"department_title"`
	Children        []Member `json:"children"`
}
