// Code generated by goctl. DO NOT EDIT.
package types

type Device struct {
	Id         int64  `json:"device_id"`
	DeviceName string `json:"device_name,optional"`
}

type PositionAddReq struct {
	PositionName string  `json:"position_name"`
	DeviceIds    []int64 `json:"device_ids,optional"`
}

type SuccessReply struct {
	Success bool `json:"success"`
}

type PageReq struct {
	Page         int    `form:"page,default=1"`
	Limit        int    `form:"limit,default=10"`
	PositionName string `form:"position_name,optional"`
}

type PositionListReply struct {
	Count     int         `json:"count"`
	Positions []*Position `json:"positions"`
}

type Position struct {
	Id           int64     `json:"position_id"`
	PositionName string    `json:"position_name"`
	ClassName    string    `json:"class_name"`
	Devices      []*Device `json:"devices"`
}

type PositionEditReq struct {
	Id           int64   `json:"position_id"`
	PositionName string  `json:"position_name"`
	ClassId      int64   `json:"class_id"`
	DeviceIds    []int64 `json:"device_ids"`
}

type PositionIdReq struct {
	Id int64 `json:"position_id"`
}

type GeneratePositionReq struct {
	WebsocketUuid string `json:"websocket_uuid"`
}
