// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: sms.proto

// protoc --go_out=plugins=grpc:. sms.proto

package sms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile  string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BaseSms) Reset() {
	*x = BaseSms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseSms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSms) ProtoMessage() {}

func (x *BaseSms) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSms.ProtoReflect.Descriptor instead.
func (*BaseSms) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSms) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *BaseSms) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile     string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Params     []string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	TemplateId string   `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SendRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{2}
}

type MultiSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string        `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Multi      []*SmsContent `protobuf:"bytes,2,rep,name=multi,proto3" json:"multi,omitempty"`
}

func (x *MultiSendRequest) Reset() {
	*x = MultiSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSendRequest) ProtoMessage() {}

func (x *MultiSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSendRequest.ProtoReflect.Descriptor instead.
func (*MultiSendRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{3}
}

func (x *MultiSendRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MultiSendRequest) GetMulti() []*SmsContent {
	if x != nil {
		return x.Multi
	}
	return nil
}

type SmsContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile     []string `protobuf:"bytes,1,rep,name=mobile,proto3" json:"mobile,omitempty"`
	TemplateId string   `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Params     []string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
}

func (x *SmsContent) Reset() {
	*x = SmsContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsContent) ProtoMessage() {}

func (x *SmsContent) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsContent.ProtoReflect.Descriptor instead.
func (*SmsContent) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{4}
}

func (x *SmsContent) GetMobile() []string {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *SmsContent) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SmsContent) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type RmqData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       int32            `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Data       string           `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	TemplateId string           `protobuf:"bytes,3,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`
	MultiMt    []*ContentMobile `protobuf:"bytes,4,rep,name=MultiMt,proto3" json:"MultiMt,omitempty"`
}

func (x *RmqData) Reset() {
	*x = RmqData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RmqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmqData) ProtoMessage() {}

func (x *RmqData) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmqData.ProtoReflect.Descriptor instead.
func (*RmqData) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{5}
}

func (x *RmqData) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RmqData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RmqData) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *RmqData) GetMultiMt() []*ContentMobile {
	if x != nil {
		return x.MultiMt
	}
	return nil
}

type ContentMobile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string   `protobuf:"bytes,1,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`
	Mobile     []string `protobuf:"bytes,2,rep,name=Mobile,proto3" json:"Mobile,omitempty"`
	Params     []string `protobuf:"bytes,3,rep,name=Params,proto3" json:"Params,omitempty"`
}

func (x *ContentMobile) Reset() {
	*x = ContentMobile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentMobile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentMobile) ProtoMessage() {}

func (x *ContentMobile) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentMobile.ProtoReflect.Descriptor instead.
func (*ContentMobile) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{6}
}

func (x *ContentMobile) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ContentMobile) GetMobile() []string {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *ContentMobile) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SmsSendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SmsSendResponse) Reset() {
	*x = SmsSendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsSendResponse) ProtoMessage() {}

func (x *SmsSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsSendResponse.ProtoReflect.Descriptor instead.
func (*SmsSendResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{7}
}

var File_sms_proto protoreflect.FileDescriptor

var file_sms_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x6d, 0x73,
	0x22, 0x3b, 0x0a, 0x07, 0x62, 0x61, 0x73, 0x65, 0x53, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5e, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x06, 0x0a,
	0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x5a, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x6d, 0x73, 0x2e,
	0x73, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x22, 0x5d, 0x0a, 0x0a, 0x73, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x22, 0x7f, 0x0a, 0x07, 0x52, 0x6d, 0x71, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d,
	0x74, 0x22, 0x5f, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x6d, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x97, 0x01, 0x0a, 0x0a, 0x53, 0x6d, 0x73, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x6e,
	0x64, 0x12, 0x15, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53,
	0x6d, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53,
	0x6d, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x0c, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x52, 0x6d, 0x71,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x09, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x42,
	0x05, 0x5a, 0x03, 0x73, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sms_proto_rawDescOnce sync.Once
	file_sms_proto_rawDescData = file_sms_proto_rawDesc
)

func file_sms_proto_rawDescGZIP() []byte {
	file_sms_proto_rawDescOnce.Do(func() {
		file_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_sms_proto_rawDescData)
	})
	return file_sms_proto_rawDescData
}

var file_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sms_proto_goTypes = []interface{}{
	(*BaseSms)(nil),          // 0: sms.baseSms
	(*SendRequest)(nil),      // 1: sms.SendRequest
	(*Null)(nil),             // 2: sms.Null
	(*MultiSendRequest)(nil), // 3: sms.MultiSendRequest
	(*SmsContent)(nil),       // 4: sms.smsContent
	(*RmqData)(nil),          // 5: sms.RmqData
	(*ContentMobile)(nil),    // 6: sms.ContentMobile
	(*SmsSendResponse)(nil),  // 7: sms.SmsSendResponse
}
var file_sms_proto_depIdxs = []int32{
	4, // 0: sms.MultiSendRequest.multi:type_name -> sms.smsContent
	6, // 1: sms.RmqData.MultiMt:type_name -> sms.ContentMobile
	3, // 2: sms.SmsHandler.MultiSend:input_type -> sms.MultiSendRequest
	1, // 3: sms.SmsHandler.Send:input_type -> sms.SendRequest
	5, // 4: sms.SmsHandler.Push:input_type -> sms.RmqData
	7, // 5: sms.SmsHandler.MultiSend:output_type -> sms.SmsSendResponse
	7, // 6: sms.SmsHandler.Send:output_type -> sms.SmsSendResponse
	2, // 7: sms.SmsHandler.Push:output_type -> sms.Null
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sms_proto_init() }
func file_sms_proto_init() {
	if File_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseSms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RmqData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentMobile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsSendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sms_proto_goTypes,
		DependencyIndexes: file_sms_proto_depIdxs,
		MessageInfos:      file_sms_proto_msgTypes,
	}.Build()
	File_sms_proto = out.File
	file_sms_proto_rawDesc = nil
	file_sms_proto_goTypes = nil
	file_sms_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SmsHandlerClient is the client API for SmsHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsHandlerClient interface {
	MultiSend(ctx context.Context, in *MultiSendRequest, opts ...grpc.CallOption) (*SmsSendResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SmsSendResponse, error)
	Push(ctx context.Context, in *RmqData, opts ...grpc.CallOption) (*Null, error)
}

type smsHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsHandlerClient(cc grpc.ClientConnInterface) SmsHandlerClient {
	return &smsHandlerClient{cc}
}

func (c *smsHandlerClient) MultiSend(ctx context.Context, in *MultiSendRequest, opts ...grpc.CallOption) (*SmsSendResponse, error) {
	out := new(SmsSendResponse)
	err := c.cc.Invoke(ctx, "/sms.SmsHandler/MultiSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsHandlerClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SmsSendResponse, error) {
	out := new(SmsSendResponse)
	err := c.cc.Invoke(ctx, "/sms.SmsHandler/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsHandlerClient) Push(ctx context.Context, in *RmqData, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := c.cc.Invoke(ctx, "/sms.SmsHandler/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsHandlerServer is the server API for SmsHandler service.
type SmsHandlerServer interface {
	MultiSend(context.Context, *MultiSendRequest) (*SmsSendResponse, error)
	Send(context.Context, *SendRequest) (*SmsSendResponse, error)
	Push(context.Context, *RmqData) (*Null, error)
}

// UnimplementedSmsHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedSmsHandlerServer struct {
}

func (*UnimplementedSmsHandlerServer) MultiSend(context.Context, *MultiSendRequest) (*SmsSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiSend not implemented")
}
func (*UnimplementedSmsHandlerServer) Send(context.Context, *SendRequest) (*SmsSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedSmsHandlerServer) Push(context.Context, *RmqData) (*Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}

func RegisterSmsHandlerServer(s *grpc.Server, srv SmsHandlerServer) {
	s.RegisterService(&_SmsHandler_serviceDesc, srv)
}

func _SmsHandler_MultiSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsHandlerServer).MultiSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.SmsHandler/MultiSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsHandlerServer).MultiSend(ctx, req.(*MultiSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsHandler_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsHandlerServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.SmsHandler/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsHandlerServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsHandler_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmqData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsHandlerServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.SmsHandler/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsHandlerServer).Push(ctx, req.(*RmqData))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmsHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sms.SmsHandler",
	HandlerType: (*SmsHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MultiSend",
			Handler:    _SmsHandler_MultiSend_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _SmsHandler_Send_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _SmsHandler_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms.proto",
}
