// Code generated by goctl. DO NOT EDIT.
package types

type ClassIdReq struct {
	ClassId int64 `json:"class_id"`
}

type PositionIdReq struct {
	PositionId int64 `json:"position_id"`
}

type MemberIdReq struct {
	MemberId int64 `json:"member_id"`
}

type ClassCourseTableReply struct {
	ClassCourses []*ClassCourse `json:"class_courses"`
}

type TeachersCourseTableReply struct {
	TeacherCourseTableInfo TeacherCourseTableInfo `json:"teacher_course_table"`
}

type ClassCourse struct {
	ClassId    int64            `json:"class_Id"`
	ClassName  string           `json:"class_name"`
	CourseList []*OrgCourseInfo `json:"course_list"`
}

type OrgCourseInfo struct {
	Weekday      int8   `json:"weekday"`
	CourseSort   int8   `json:"course_sort"`
	SubjectName  string `json:"subject_name"`
	TeacherName  string `json:"teacher_name"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	PositionName string `json:"position_name,omitempty"`
	ClassName    string `json:"class_name,omitempty"`
	CourseNote   string `json:"course_note"`
}

type TeacherCourseTableInfo struct {
	Classes []*OrgCourseInfo `json:"course_info"`
}

type CourseInfo struct {
	Id           int64  `json:"id,omitempty"`
	CourseSort   int8   `json:"course_sort,omitempty"`
	ClassId      int64  `json:"class_id,omitempty"`
	ClassName    string `json:"class_name,omitempty"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	CourseName   string `json:"course_name,omitempty"`
	PositionName string `json:"position_name,omitempty"`
	TeacherName  string `json:"teacher_name,omitempty"`
	CourseFlag   int8   `json:"course_flag,omitempty"`
	SubjectName  string `json:"subject_name,omitempty"`
	SubjectId    int64  `json:"subject_id,omitempty"`
}

type PositionCourseTableReply struct {
	PositionId              int64            `json:"position_id"`
	PositionName            string           `json:"position_name"`
	PositionCourseTableInfo []*OrgCourseInfo `json:"position_course_table_info"`
}

type PositionCourseTableInfo struct {
	CourseInfo []*CourseInfo `json:"course_info"`
}

type CourseTableDeployReply struct {
	DeployInfo []*DeployInfo `json:"deploy_info"`
}

type DeployInfo struct {
	Weekday          int8                `json:"weekday"`
	CourseDeployInfo []*CourseDeployInfo `json:"course_deploy_info"`
}

type CourseDeployInfo struct {
	Id         int64  `json:"id,optional"`
	Weekday    int8   `json:"weekday,omitempty"`
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
	Note       string `json:"note"`
	CourseSort int8   `json:"course_sort,optional"`
	Grouping   int8   `json:"grouping,optional"`
	CourseFlag int8   `json:"course_flag"`
}

type CourseTableDeploySaveReq struct {
	DeployInfo []*CourseDeployInfo `json:"course_deploy_info"`
}

type BoolReply struct {
	Success bool `json:"success"`
}

type DeployGenerateReq struct {
	MorningStartTime          string `json:"morning_start_time"`
	MorningCourseTime         int8   `json:"morning_course_time"`
	MorningRecessTime         int8   `json:"morning_recess_time"`
	AfternoonStartTime        string `json:"afternoon_start_time"`
	AfternoonCourseTime       int8   `json:"afternoon_course_time"`
	AfternoonRecessTime       int8   `json:"afternoon_recess_time"`
	MorningRecessIndex        int8   `json:"morning_recess_index"`
	AfternoonRecessIndex      int8   `json:"afternoon_recess_index"`
	BreakTime                 int8   `json:"break_time"`
	MorningCourseCount        int8   `json:"morning_course_count"`
	AfternoonCourseCount      int8   `json:"afternoon_course_count"`
	MorningSelfStudyCount     int8   `json:"morning_self_study_count"`
	NightSelfStudyCount       int8   `json:"night_self_study_count"`
	MorningSelfStudyTime      int8   `json:"morning_self_study_time,optional"`
	NightSelfStudyTime        int8   `json:"night_self_study_time,optional"`
	MorningSelfStudyStartTime string `json:"morning_self_study_start_time"`
	NightSelfStudyStartTime   string `json:"night_self_study_start_time"`
}

type DeployGenerateReply struct {
	CourseTableDeploy []*CourseTableGenerate `json:"course_table_deploy"`
}

type CourseTableGenerate struct {
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
	Note       string `json:"note"`
	Weekday    int8   `json:"weekday"`
	CourseSort int8   `json:"course_sort,omitempty"`
	Grouping   int8   `json:"grouping,omitempty"`
	CourseFlag int8   `json:"course_flag"`
}

type CourseTableInfoReq struct {
	PositionId int64 `json:"position_id"`
}

type CourseTableInfo struct {
	Weekday    int8          `json:"weekday"`
	CourseInfo []*CourseInfo `json:"course_info"`
}

type CourseTableInfoReply struct {
	PositionName string             `json:"position_name"`
	ClassId      int64              `json:"class_id"`
	ClassName    string             `json:"class_name"`
	CourseTable  []*CourseTableInfo `json:"coursetable"`
}

type CourseTableAddReq struct {
	PositionId int64 `json:"position_id"`
	ClassId    int64 `json:"class_id"`
	SubjectId  int64 `json:"subject_id"`
	Weekday    int8  `json:"weekday"`
	CourseSort int8  `json:"course_sort"`
}

type StudentCourseTable struct {
	StudentName     string             `json:"student_name"`
	Username        string             `json:"username"`
	ClassName       string             `json:"class_name"`
	CourseTableInfo []*CourseTableInfo `json:"course_table_info"`
}

type StudentTableReply struct {
	StudentCourseTables []*StudentCourseTable `json:"student_course_tables"`
}

type PageReq struct {
	Page  int `form:"page,default=1"`
	Limit int `form:"limit,default=10"`
}

type OrgCourseTableReply struct {
	OrgCourseTable []*OrgCourseTable `json:"org_course_table"`
}

type OrgCourseTable struct {
	Weekday    int8          `json:"weekday"`
	CourseSort int8          `json:"course_sort"`
	Note       string        `json:"note"`
	CourseInfo []*CourseInfo `json:"course_info"`
}

type MyCourseTableReq struct {
	Type      int   `json:"type"`
	StudentId int64 `json:"student_id,optional"`
	MemberId  int64 `json:"member_id,optional"`
}

type Id struct {
	Id int64 `json:"id"`
	*PageListReq
}

type PageListReq struct {
	StageId     int64  `json:"stage_id,optional"`
	GradeId     int64  `json:"grade_id,optional"`
	ClassId     int64  `json:"class_id,optional"`
	TeacherName string `json:"teacher_name,optional"`
	Page        int    `json:"page,optional,defult=1"`
	Limit       int    `json:"limit,optional,default=15"`
}

type AddTeachReq struct {
	ClassId   int64 `json:"class_id"`
	SubjectId int64 `json:"subject_id"`
	TeacherId int64 `json:"teacher_id"`
}

type UpdateTeachReq struct {
	ClassId   int64 `json:"class_id"`
	SubjectId int64 `json:"subject_id"`
	TeacherId int64 `json:"teacher_id"`
}

type TeachResp struct {
	Id           int64  `json:"id"`
	ClassId      int64  `json:"class_id"`
	SubjectId    int64  `json:"subject_id"`
	SubjectTitle string `json:"subject_title"`
	TeacherId    int64  `json:"teacher_id"`
	TeacherName  string `json:"teacher_name"`
}

type DeleteTeachReq struct {
	Ids []int64 `json:"ids"`
}

type ListTeachResp struct {
	List []TeachResp `json:"list"`
}

type Info struct {
	Id    int64  `json:"id"`
	Title string `json:"title"`
}
