// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/datacenter/parent/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/parent/insert",
				Handler: insertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/parent/update",
				Handler: updateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/parent/delete",
				Handler: deleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/parent/page-list",
				Handler: parentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/parent/detail",
				Handler: parentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/parent/import",
				Handler: importParentsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
