// Code generated by goctl. DO NOT EDIT!
// Source: websocket.proto

package server

import (
	"context"

	"demacia/service/websocket/rpc/internal/logic"
	"demacia/service/websocket/rpc/internal/svc"
	"demacia/service/websocket/rpc/websocket"
)

type WebsocketServer struct {
	svcCtx *svc.ServiceContext
}

func NewWebsocketServer(svcCtx *svc.ServiceContext) *WebsocketServer {
	return &WebsocketServer{
		svcCtx: svcCtx,
	}
}

func (s *WebsocketServer) Push(ctx context.Context, in *websocket.Request) (*websocket.Null, error) {
	l := logic.NewPushLogic(ctx, s.svcCtx)
	return l.Push(in)
}
