// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demacia/datacenter/department/api/internal/svc"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/department/list",
				Handler: listHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/insert",
				Handler: insertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/update",
				Handler: updateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/del",
				Handler: delHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/sort",
				Handler: sortHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/members",
				Handler: memberByDepartmentIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/member/del",
				Handler: memberDeleteFromDepartmentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/department/member/insert",
				Handler: memberInsertIntoDepartmentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
