// Code generated by goctl. DO NOT EDIT.
package types

type Token struct {
	AccessToken   string `json:"access_token"`
	AccessExpire  int64  `json:"access_expire"`
	RefreshToken  string `json:"refresh_token"`
	RefreshExpire int64  `json:"refresh_expire"`
	RefreshAfter  int64  `json:"refresh_after"`
}

type LoginRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type TokenResponse struct {
	Token Token `json:"token"`
}
