// Code generated by goctl. DO NOT EDIT!
// Source: subject.proto

package server

import (
	"context"

	"demacia/datacenter/subject/rpc/internal/logic"
	"demacia/datacenter/subject/rpc/internal/svc"
	"demacia/datacenter/subject/rpc/subject"
)

type SubjectServer struct {
	svcCtx *svc.ServiceContext
}

func NewSubjectServer(svcCtx *svc.ServiceContext) *SubjectServer {
	return &SubjectServer{
		svcCtx: svcCtx,
	}
}

func (s *SubjectServer) GetSubjectById(ctx context.Context, in *subject.IdReq) (*subject.SubjectInfo, error) {
	l := logic.NewGetSubjectByIdLogic(ctx, s.svcCtx)
	return l.GetSubjectById(in)
}
