// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"demacia/cloudscreen/courserecord/api/internal/svc"
	"net/http"

	"gitlab.u-jy.cn/xiaoyang/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/add",
					Handler: courseRecordAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/record",
					Handler: courseRecordSignHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/courserecord/config_info",
					Handler: courseRecordConfigInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/config_save",
					Handler: courseRecordConfigSaveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/count",
					Handler: courseRecordCountHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/init",
					Handler: findClassCourseRecordInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/class_record",
					Handler: GetClassCourseRecordListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/courserecord/my_record",
					Handler: GetCourseRecordListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
