// Code generated by goctl. DO NOT EDIT!
// Source: coursetable.proto

package server

import (
	"context"

	"demacia/datacenter/coursetable/rpc/coursetable"
	"demacia/datacenter/coursetable/rpc/internal/logic"
	"demacia/datacenter/coursetable/rpc/internal/svc"
)

type CoursetableServer struct {
	svcCtx *svc.ServiceContext
}

func NewCoursetableServer(svcCtx *svc.ServiceContext) *CoursetableServer {
	return &CoursetableServer{
		svcCtx: svcCtx,
	}
}

func (s *CoursetableServer) GetCourseTableDeployListByOrgId(ctx context.Context, in *coursetable.OrgIdReq) (*coursetable.CourseTableDeployResp, error) {
	l := logic.NewGetCourseTableDeployListByOrgIdLogic(ctx, s.svcCtx)
	return l.GetCourseTableDeployListByOrgId(in)
}

func (s *CoursetableServer) GetCourseTableInfoByOrgIdAndSort(ctx context.Context, in *coursetable.CourseInfoReq) (*coursetable.CourseTableInfoResp, error) {
	l := logic.NewGetCourseTableInfoByOrgIdAndSortLogic(ctx, s.svcCtx)
	return l.GetCourseTableInfoByOrgIdAndSort(in)
}

func (s *CoursetableServer) GetCourseTableRecordInfo(ctx context.Context, in *coursetable.OrgIdAndClassIdReq) (*coursetable.CourseTableRecordResp, error) {
	l := logic.NewGetCourseTableRecordInfoLogic(ctx, s.svcCtx)
	return l.GetCourseTableRecordInfo(in)
}

func (s *CoursetableServer) RemoveCourseTeacher(ctx context.Context, in *coursetable.ClassIdAndMemberIdReq) (*coursetable.SuccessResp, error) {
	l := logic.NewRemoveCourseTeacherLogic(ctx, s.svcCtx)
	return l.RemoveCourseTeacher(in)
}

func (s *CoursetableServer) UpdateCourseTeacher(ctx context.Context, in *coursetable.ClassIdAndMemberInfoReq) (*coursetable.SuccessResp, error) {
	l := logic.NewUpdateCourseTeacherLogic(ctx, s.svcCtx)
	return l.UpdateCourseTeacher(in)
}
