// Code generated by goctl. DO NOT EDIT!
// Source: websocket.proto

package websocketclient

import (
	"context"

	"demacia/service/websocket/rpc/websocket"

	"gitlab.u-jy.cn/xiaoyang/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Null    = websocket.Null
	Request = websocket.Request

	Websocket interface {
		Push(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Null, error)
	}

	defaultWebsocket struct {
		cli zrpc.Client
	}
)

func NewWebsocket(cli zrpc.Client) Websocket {
	return &defaultWebsocket{
		cli: cli,
	}
}

func (m *defaultWebsocket) Push(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Null, error) {
	client := websocket.NewWebsocketClient(m.cli.Conn())
	return client.Push(ctx, in, opts...)
}
