// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"demacia/datacenter/user/rpc/internal/logic"
	"demacia/datacenter/user/rpc/internal/svc"
	"demacia/datacenter/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) FindOneByUserName(ctx context.Context, in *user.UserNameReq) (*user.UserInfo, error) {
	l := logic.NewFindOneByUserNameLogic(ctx, s.svcCtx)
	return l.FindOneByUserName(in)
}
