unit test:
  extends:
    - .merge_request_pipelines
  before_script:
    - cp -r /builds/runeterra/demacia /demacia
    - cd /demacia
  stage: test
  parallel: 5
  script:
    - source .gitlab/scripts/touch_make_dependencies
    - make -f $MAKEFILE_PATH parallel_test_execute
  after_script:
    - pwd
    - cp -r /demacia/.cover $CI_PROJECT_DIR/
    - cp -r /demacia/.testoutput $CI_PROJECT_DIR/
  artifacts:
    paths:
      - .cover/*
      - .testoutput/*
    when: always
    expire_in: 1h

unit test with race:
  extends:
    - unit test
  allow_failure: true
  variables:
    CGO_ENABLED: "1"
    TESTFLAGS: "-cover -race"
